### ISSUE TITLE
Evaluate phpdox

### ISSUE THREAD

**Issue by mootari** [mootari/kayak#5]
Requirements:
- Implement JSON export for [phpdox](http://phpdox.de/).
- Implement exporting of a complete class hierarchy.
- Document available data structures.
- Decide if individual JSON files are suitable for direct consumption by frontend code.

**Comment by cisso** [comment]
A custom engine was implemented for JSON export. Currently only the index is produced (although with added dependency information) , tokens and bodies (individual class/interface/trait files) are skipped.

To keep phpdox from choking inexplicably, and to be able to load various parts of the index separately, indexing has been split into:
- lib (core/lib, core/tests) 
- add-ons (core/modules, core/profiles, core/themes) 
- vendor (vendor) 

There are still some errors popping up for trait references, nothing game-breaking though. Also, cross (phpdox-) project index references have to be added for inheritance resolution (probably only needed for direct looking between json files).

**Comment by mootari** [comment]
Switched to ApiGen due to superior API.
