### ISSUE TITLE
Parsing: Find/filter package source files

### ISSUE THREAD

**Issue by mootari** [mootari/kayak#8]
Once a package has been downloaded (prior to generating the docs) we need to determine what files to parse. There are multiple approaches we could take:
  1. Assume the whole package content needs to be parsed.
  2. Assume the /src convention is used and limit parsing to that directory.
  3. Base the list of targeted files on the package's autoload config.

**Comment by Uhkis** [comment]
1. Because the .module file needs to be parsed also.

**Comment by cisso** [comment]
That implies that we'll also expose functions through the UI. Hm.
Keep in mind that the choice we make has to be appropriate for any type of composer package, not just Drupal modules (since dependencies will also be parsed and exposed).

**Comment by Uhkis** [comment]
> That implies that we'll also expose functions through the UI

I can't think of any problems with this?


>Keep in mind that the choice we make has to be appropriate for any type of composer package, not just Drupal modules 

Of course. Can we distinguish Drupal packages from regular composer packages somehow? I don't think many non-Drupal packages have .module files, parser could be configured to /src + *.module?

**Comment by mootari** [comment]
We can tell them apart by the package vendor, as all Drupal modules will likely start with "drupal/". I guess we can roll with 1. and see if we hit any problems.
